ido-version/main/default/objects/Q_Industries_Version_Info__mdt/Q_Industries_Version_Info__mdt.object-meta.xml
<CustomObject>
    <description>Contains version information about the IDO</description>
    <label>Q Industries Version Info</label>
    <pluralLabel>Q Industries Version Info</pluralLabel>
</CustomObject>

ido-version/main/default/objects/Q_Industries_Version_Info__mdt/fields/Core_Release_Name__c.field-meta.xml
<CustomField>
    <fullName>Core_Release_Name__c</fullName>
    <description>Seasonal release name e.g. Summer &#39;20</description>
    <label>Core Release Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-version/main/default/objects/Q_Industries_Version_Info__mdt/fields/Core_Release_Number__c.field-meta.xml
<CustomField>
    <fullName>Core_Release_Number__c</fullName>
    <description>Core release number that this IDO is based on e.g. 220</description>
    <label>Core Release Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ido-version/main/default/objects/Q_Industries_Version_Info__mdt/fields/IDO_Release_Name__c.field-meta.xml
<CustomField>
    <fullName>IDO_Release_Name__c</fullName>
    <description>IDO release name e.g. RCG IDO Summer &#39;20 R1</description>
    <inlineHelpText>IDO release name e.g. RCG IDO Summer &#39;20 R1</inlineHelpText>
    <label>IDO Release Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ido-version/main/default/objects/Q_Industries_Version_Info__mdt/fields/SDO_Trialforce_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>SDO_Trialforce_Template_ID__c</fullName>
    <description>If based on the SDO, which SDO trialforce template ID is this IDO based on</description>
    <label>SDO Trialforce Template ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ido-version/main/default/classes/IDOVersionController.cls
public with sharing class IDOVersionController {

    private static final String DEFAULT_RECORD_NAME = 'ReleaseInfo';

    @AuraEnabled (cacheable=true)
    public static Q_Industries_Version_Info__mdt getVersionInfo() {
        Q_Industries_Version_Info__mdt metaData;
        metaData = [SELECT ID, MasterLabel, DeveloperName, Language, Core_Release_Name__c, Core_Release_Number__c, IDO_Release_Name__c, SDO_Trialforce_Template_ID__c FROM Q_Industries_Version_Info__mdt WHERE DeveloperName = :DEFAULT_RECORD_NAME];
        return metaData;
    }
}